### ISSUE TITLE
live-reload-server (frontend) cannot start

### ISSUE THREAD

**Issue by alexsongrj** [Merck/Mutation_Maker#15]
Hi Team, really appreciated such a nice open source project.

I am trying to run live-reload-server frontend where I changed the docker-compose.yml file targeting to live-reload-server and rebuild the docker image but it does not work with the below error while I docker-compose up:

  frontend_1   | ℹ ｢wds｣: Project is running at http://172.18.0.6/
  frontend_1   | ℹ ｢wds｣: webpack output is served from
  frontend_1   | ℹ ｢wds｣: Content not from webpack is served from /frontend/public
  frontend_1   | ℹ ｢wds｣: 404s will fallback to /
  frontend_1   | Starting the development server...
  frontend_1   |
  mutation_maker-master_frontend_1 exited with code 0

when I build the docker it has some warning shown in below: 

  Building frontend
  Step 1/7 : FROM node:12.13.1-alpine as live-reload-server
   ---> 3fb8a14691d9
  Step 2/7 : LABEL maintainer="Mutation Maker https://github.com/Merck/Mutation_Maker"
   ---> Using cache
   ---> e8e4b4755554
  Step 3/7 : COPY ./ /frontend/
   ---> 33e3a1bc7ad1
  Step 4/7 : WORKDIR /frontend/
   ---> Running in 5ef596d5f262
  Removing intermediate container 5ef596d5f262
   ---> 6de251ae3701
  Step 5/7 : RUN npm ci
   ---> Running in 72003c23487c
  
  > core-js@2.6.11 postinstall /frontend/node_modules/core-js
  > node -e "try{require('./postinstall')}catch(e){}"
  
  Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
  
  The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
  > https://opencollective.com/core-js 
  > https://www.patreon.com/zloirock 
  
  Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

I am not sure whether this caused the failure of live-reload-server start.
Hope you could help me with this thanks. If you need other info please let me know !

**Comment by ra100** [comment]
Hi, can you provide details, how you've run it?

**Comment by alexsongrj** [comment]
I ran it under Windows 10 using VScode.

so I enable live-reload-server
# Select live-reload-server target for the development npm server with live reload
      target: live-reload-server

then in power shell I run:

docker-compose build 
docker-compose up

**Comment by prihoda** [comment]
Hi @alexsongrj, I think there's no advantage of running the live reload server through Docker, since it won't live reload anyway - you'll need to build and run the image each time you make changes. See the Running locally section to set up a development environment with live reload https://github.com/Merck/Mutation_Maker#running-locally. 

Am I right @ra100? Also, shall we update our README, since we're now using the production server as default in docker compose? https://github.com/Merck/Mutation_Maker#configuring-docker-frontend-live-reload-or-production-ready-build

**Comment by ra100** [comment]
@prihoda right, for the frontend live-reload, just running it locally and the rest through docker-compose should work just fine. If you want to change just the FE.
And the README would use some love :)

**Comment by alexsongrj** [comment]
@prihoda @ra100  I ran it locally, it works! Really appreciate your prompt response!

**Comment by ra100** [comment]
@alexsongrj you're welcome, so I guess, I can close this issue :)

**Comment by alexsongrj** [comment]
@ra100 yes please, thanks for your help !
