### ISSUE TITLE
frontend docker build failing

### ISSUE THREAD

**Issue by JunaidChaudry** [Merck/Mutation_Maker#8]
I am trying to run the project using docker-compose, but the frontend Docker build keeps failing on the step `RUN npm run build` with a JavaScript heap out of memory message... I have tried specifying --max_old_space_size=4096, as well as 8090 and 12900, but it still fails... See the image below for the complete error message, and the stack trace while running with the stock code that's on github...

![image](https://user-images.githubusercontent.com/49313431/100012763-cb604280-2da1-11eb-9d3c-6f3bd125ad96.png)

How to recreate the problem: 
- run `docker-compose up --build`, or just build the frontend docker image

**Comment by swiewiora** [comment]
What is your OS with its version and version of Docker installed?

**Comment by JunaidChaudry** [comment]
I am using a MacOS Cataline Version 10.15.7,, with Docker Desktop Community Version 2.3.7.0 Channel edge.. 

 I have also tried it through Jenkins running on aws, which also returns the exact same response

**Comment by prihoda** [comment]
Hi @JunaidChaudry, you can also try increasing your memory limit in Docker preferences:

![image](https://user-images.githubusercontent.com/2894124/100371108-92c1a280-3007-11eb-8939-a13ea8b087ba.png)

**Comment by swiewiora** [comment]
I reproduced the issue on macOS 10.15.7 (19H15) with Docker 2.5.0.0 (49427) with 2GB RAM. After increasing memory to 3GB RAM the issue went away. 

This option is unavailable on Docker running on Windows with WSL 2 VM enabled and require changing global WSL option:
https://docs.microsoft.com/en-us/windows/wsl/wsl-config#wsl-2-settings

**Comment by JunaidChaudry** [comment]
Increasing the memory for docker also fixed the issue for me.. Thanks for the help
